"""Build `claims.gbnf` FROM the schema, and a matcher for the subset it uses.

Two problems this solves.

1. DRIFT. A hand-written grammar and a Python schema will diverge, silently,
   the first time a key is added. So the grammar is generated from the same
   constants the verifier uses, and `tests/test_grammar_agreement.py` asserts
   the committed file is byte-identical to what this produces. They cannot
   disagree, because there is only one source.

2. AGREEMENT IS UNTESTABLE WITHOUT A RECOGNISER. "The grammar accepts exactly
   the syntactically valid claim space" is a claim about a grammar, and
   checking it needs something that can run the grammar. `Grammar.matches`
   implements the small GBNF subset used here - literals, alternation,
   sequence, grouping, `?`/`*`/`+`, and character classes - so the test can
   enumerate claims and compare acceptance against the schema directly.

The grammar is written as a UNION OF PER-TYPE PRODUCTIONS rather than one
generic claim object. GBNF is context-free, so each type's exact field set,
field order and enum values are expressible at the token level - which makes
malformed per-type output UNGENERATABLE rather than merely rejected. That is
the closed-world principle applied to decoding.

It goes further where it can: `value` and `hedged_value` may only cite the 17
NUMERIC evidence ids, and `review_flag` may only cite the 2 tier ids. Those are
per-type id restrictions a context-free grammar can enforce, so a model
physically cannot emit a `value` claim about `night.confidence`.

What the grammar CANNOT do, and Layer 1 therefore must: `claim_id` uniqueness,
and any agreement between two fields of the same claim (a unit matching the
cited id). Those need state.
"""
from __future__ import annotations

import re
from pathlib import Path

from .claim_schema import (EVIDENCE_ID_VOCAB, REASON_KEYS, TEXT_KEYS,
                           TIER_ITEMS)

HERE = Path(__file__).resolve().parent
GBNF_PATH = HERE / "claims.gbnf"

NUMERIC_IDS = tuple(i for i in EVIDENCE_ID_VOCAB if i not in TIER_ITEMS)
TIER_IDS = tuple(i for i in EVIDENCE_ID_VOCAB if i in TIER_ITEMS)

# Units that can appear on a numeric item. "tier" is deliberately absent:
# tier items are not citeable by value/hedged_value at all.
NUMERIC_UNITS = ("minutes", "fraction", "count", "per hour", "ratio")


def _alt(strings) -> str:
    return " | ".join(f'"\\"{s}\\""' for s in strings)


def build_grammar() -> str:
    lines = [
        "# GENERATED by report/gbnf.py from report/claim_schema.py.",
        "# Do not edit by hand - tests/test_grammar_agreement.py asserts this",
        "# file is byte-identical to the generated text, so an edit here fails",
        "# the suite rather than silently diverging from the verifier.",
        "#",
        "# Union of per-type productions: each claim type has its own exact",
        "# field set, field order and enums, so malformed per-type output is",
        "# ungeneratable rather than merely rejected.",
        "",
        'root ::= "[" ws (claim (ws "," ws claim)* ws)? "]"',
        "",
        "claim ::= value-claim | hedged-claim | observation-claim "
        "| review-claim | assoc-claim",
        "",
        "# ---- value: exactly one NUMERIC evidence id ----------------------",
        'value-claim ::= "{" ws claim-id ws "," ws '
        '"\\"claim_type\\"" ws ":" ws "\\"value\\"" ws "," ws '
        'numeric-cites ws "," ws this-recording ws "," ws '
        'value-field ws "," ws unit-field ws "}"',
        "",
        "# ---- hedged_value: identical shape, different type token ---------",
        'hedged-claim ::= "{" ws claim-id ws "," ws '
        '"\\"claim_type\\"" ws ":" ws "\\"hedged_value\\"" ws "," ws '
        'numeric-cites ws "," ws this-recording ws "," ws '
        'value-field ws "," ws unit-field ws "}"',
        "",
        "# ---- observation: one or more ids, plus a predicate-bound key ----",
        'observation-claim ::= "{" ws claim-id ws "," ws '
        '"\\"claim_type\\"" ws ":" ws "\\"observation\\"" ws "," ws '
        'any-cites ws "," ws this-recording ws "," ws '
        'text-key-field ws "}"',
        "",
        "# ---- review_flag: exactly one TIER id ----------------------------",
        'review-claim ::= "{" ws claim-id ws "," ws '
        '"\\"claim_type\\"" ws ":" ws "\\"review_flag\\"" ws "," ws '
        'tier-cites ws "," ws this-recording ws "," ws '
        'reason-key-field ws "}"',
        "",
        "# ---- population_association: subject is population ---------------",
        'assoc-claim ::= "{" ws claim-id ws "," ws '
        '"\\"claim_type\\"" ws ":" ws "\\"population_association\\"" ws "," ws '
        'any-cites ws "," ws population ws "}"',
        "",
        'claim-id ::= "\\"claim_id\\"" ws ":" ws "\\"c" digits "\\""',
        'this-recording ::= "\\"subject\\"" ws ":" ws "\\"this_recording\\""',
        'population ::= "\\"subject\\"" ws ":" ws "\\"population\\""',
        'value-field ::= "\\"value\\"" ws ":" ws number',
        f'unit-field ::= "\\"unit\\"" ws ":" ws ({_alt(NUMERIC_UNITS)})',
        f'text-key-field ::= "\\"text_key\\"" ws ":" ws ({_alt(sorted(TEXT_KEYS))})',
        f'reason-key-field ::= "\\"reason_key\\"" ws ":" ws '
        f'({_alt(sorted(REASON_KEYS))})',
        "",
        'numeric-cites ::= "\\"cites\\"" ws ":" ws "[" ws numeric-id ws "]"',
        'tier-cites ::= "\\"cites\\"" ws ":" ws "[" ws tier-id ws "]"',
        'any-cites ::= "\\"cites\\"" ws ":" ws "[" ws any-id '
        '(ws "," ws any-id)* ws "]"',
        "",
        f"numeric-id ::= {_alt(NUMERIC_IDS)}",
        "",
        f"tier-id ::= {_alt(TIER_IDS)}",
        "",
        "any-id ::= numeric-id | tier-id",
        "",
        "digits ::= [0-9]+",
        'number ::= "-"? [0-9]+ ("." [0-9]+)?',
        'ws ::= [ \\t\\n]*',
        "",
    ]
    return "\n".join(lines)


def write_grammar(path: Path = GBNF_PATH) -> Path:
    path.write_text(build_grammar(), encoding="utf-8", newline="\n")
    return path


# ==========================================================================
# A matcher for the GBNF subset above.
# ==========================================================================
_TOKEN = re.compile(r"""
      (?P<str>"(?:\\.|[^"\\])*")
    | (?P<cls>\[(?:\\.|[^\]\\])*\])
    | (?P<name>[A-Za-z][A-Za-z0-9_-]*)
    | (?P<sym>[()|*+?])
""", re.VERBOSE)


class _Node:
    __slots__ = ("kind", "value", "children")

    def __init__(self, kind, value=None, children=()):
        self.kind = kind
        self.value = value
        self.children = list(children)


class Grammar:
    """Parses the GBNF subset and matches strings against it (backtracking)."""

    def __init__(self, text: str):
        self.rules: dict[str, _Node] = {}
        for line in text.splitlines():
            line = line.split("#")[0].strip() if line.strip().startswith("#") else line
            if "::=" not in line:
                continue
            name, body = line.split("::=", 1)
            self.rules[name.strip()] = self._parse_alt(self._tokens(body))

    # ---- parsing --------------------------------------------------------
    @staticmethod
    def _tokens(s: str) -> list[str]:
        out, i = [], 0
        while i < len(s):
            if s[i].isspace():
                i += 1
                continue
            m = _TOKEN.match(s, i)
            if not m:
                raise ValueError(f"bad token at {s[i:i + 20]!r}")
            out.append(m.group(0))
            i = m.end()
        return out

    def _parse_alt(self, toks: list[str]) -> _Node:
        branches, cur = [], []
        depth = 0
        for t in toks:
            if t == "(":
                depth += 1
            elif t == ")":
                depth -= 1
            if t == "|" and depth == 0:
                branches.append(cur)
                cur = []
            else:
                cur.append(t)
        branches.append(cur)
        if len(branches) == 1:
            return self._parse_seq(branches[0])
        return _Node("alt", children=[self._parse_seq(b) for b in branches])

    def _parse_seq(self, toks: list[str]) -> _Node:
        items, i = [], 0
        while i < len(toks):
            t = toks[i]
            if t == "(":
                depth, j = 1, i + 1
                while j < len(toks) and depth:
                    if toks[j] == "(":
                        depth += 1
                    elif toks[j] == ")":
                        depth -= 1
                    j += 1
                node = self._parse_alt(toks[i + 1:j - 1])
                i = j
            elif t.startswith('"'):
                node = _Node("lit", self._unquote(t))
                i += 1
            elif t.startswith("["):
                node = _Node("cls", t)
                i += 1
            else:
                node = _Node("ref", t)
                i += 1
            while i < len(toks) and toks[i] in ("*", "+", "?"):
                node = _Node(toks[i], children=[node])
                i += 1
            items.append(node)
        return _Node("seq", children=items)

    @staticmethod
    def _unquote(tok: str) -> str:
        body = tok[1:-1]
        return (body.replace('\\"', '"').replace("\\\\", "\\")
                .replace("\\n", "\n").replace("\\t", "\t"))

    # ---- matching -------------------------------------------------------
    @staticmethod
    def _class_match(cls: str, ch: str) -> bool:
        body = cls[1:-1]
        i, items = 0, []
        while i < len(body):
            if body[i] == "\\":
                items.append(("c", {"n": "\n", "t": "\t"}.get(body[i + 1], body[i + 1])))
                i += 2
            elif i + 2 < len(body) and body[i + 1] == "-":
                items.append(("r", (body[i], body[i + 2])))
                i += 3
            else:
                items.append(("c", body[i]))
                i += 1
        for kind, v in items:
            if kind == "c" and ch == v:
                return True
            if kind == "r" and v[0] <= ch <= v[1]:
                return True
        return False

    def _match(self, node: _Node, s: str, pos: int):
        """Yield every end position this node can consume to."""
        k = node.kind
        if k == "lit":
            if s.startswith(node.value, pos):
                yield pos + len(node.value)
        elif k == "cls":
            if pos < len(s) and self._class_match(node.value, s[pos]):
                yield pos + 1
        elif k == "ref":
            yield from self._match(self.rules[node.value], s, pos)
        elif k == "alt":
            for c in node.children:
                yield from self._match(c, s, pos)
        elif k == "seq":
            def walk(i, p):
                if i == len(node.children):
                    yield p
                    return
                for q in self._match(node.children[i], s, p):
                    yield from walk(i + 1, q)
            yield from walk(0, pos)
        elif k == "?":
            yield pos
            yield from self._match(node.children[0], s, pos)
        elif k in ("*", "+"):
            seen = {pos}
            if k == "*":
                yield pos
            frontier = [pos]
            first = True
            while frontier:
                nxt = []
                for p in frontier:
                    for q in self._match(node.children[0], s, p):
                        if q in seen and q == p:
                            continue
                        if q not in seen or True:
                            yield q
                        if q not in seen:
                            seen.add(q)
                            nxt.append(q)
                frontier = nxt
                first = False

    def matches(self, s: str, rule: str = "root") -> bool:
        return any(end == len(s) for end in self._match(_Node("ref", rule), s, 0))
